<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="" skips="0" tests="0" time="4.924"><testcase classname="scripts.FileUpload.CheckFileUpload" name="test_local_upload" time="4.28432893753"><error message="test setup failure">self = &lt;FileUpload.CheckFileUpload object at 0x101af8b90&gt;
method = &lt;bound method CheckFileUpload.test_local_upload of &lt;FileUpload.CheckFileUpload object at 0x101af8b90&gt;&gt;

    def setup_method(self, method):
        super(type(self), self).setup_method(method)
&gt;       self.u = Upload().open().wait_until_loaded()

scripts/FileUpload.py:8: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;pages.upload.Upload object at 0x101af8e10&gt;

    def __init__(self):
&gt;       super(type(self), self).__init__()

modules/pages/upload.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;pages.upload.Upload object at 0x101af8e10&gt;

    def __init__(self):
        if not hasattr(self, &apos;selenium&apos;):
&gt;           print(SeleniumWrapper().running)
E           AttributeError: &apos;SeleniumWrapper&apos; object has no attribute &apos;running&apos;

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/saunter/po/remotecontrol/page.py:30: AttributeError</error></testcase></testsuite>